module Jojo
  class CLI < Thor
    include OverwriteHelper

    def self.exit_on_failure?: () -> true

    def version: () -> untyped

    def setup: () -> untyped

    def new: () -> untyped

    def annotate: () -> untyped

    def generate: () -> untyped

    def research: () -> untyped

    def resume: () -> untyped

    def cover_letter: () -> untyped

    def website: () -> untyped

    def test: () -> untyped

    private

    def resolve_slug: () -> untyped

    def invoked_command: () -> untyped
  end
end
